deploy:
  remote:
    user: user-name
    host: paliari.com.br
    path: /home/isse/app/api
  publish:
    # choice git|scp|script
    git:
      url: git@git.paliari.com.br:paliari/paliari-deploy.git
      branch: master
    scp:
      path: .|dist
    script: heroku a b
  hooks:
    repo:
      - echo call 1 in the repo
      - echo call 2 in the repo
    releases:
      - echo call 1 in the release
      - echo call 2 in the release
